name: build_python

on:
  # schedule:
  #   - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  Bundle:
    runs-on: macos-latest
    timeout-minutes: 40
    env:
      ___X_CMD_GHACTION_X: x1
      # ___X_CMD_PKG_VERSION: ${{ github.event.inputs.x-cmd-pkg-version }}
      # ___X_CMD_PKG_BRANCH: ${{ github.event.inputs.x-cmd-pkg-branch }}
      # ___X_BASH_PKG_BRANCH: ${{ github.event.inputs.x-bash-pkg-branch }}
      # ___X_BASH_ENV_BRANCH: ${{ github.event.inputs.x-bash-env-branch }}
      WEBHOOK_URL: ${{ secrets.ROBOT }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            git pull
            git switch build_python
            git pull origin build_python
            x ws build_python && x ws push test_doc



