
name: gen web_data
on:
  workflow_dispatch:
  schedule:
    - cron: '40 6 * * *'  # 15
    - cron: '40 9 * * *'
    - cron: '10 11 * * *'
    - cron: '40 13 * * *'
    - cron: '00 18 * * *'
    - cron: '00 20 * * *'

jobs:
  Bundle:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      ___X_CMD_GHACTION_X: x2
      WEBHOOK_URL: ${{ secrets.ROBOT }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            xws gen-webdata
