name: release x-cmd pkg

on:
  # schedule:
  #   - cron: '0 18 * * *'
  workflow_dispatch:
    inputs:
      x_cmd_pkg_version:
        description: 'x-cmd pkg version'
        required: true
        default: 'v0.0.2'
jobs:
  Bundle:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      ___X_CMD_GHACTION_X: x1
      WEBHOOK_URL: ${{ secrets.ROBOT }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      # git_user: agent-zero
      # git_email: 0@x-cmd.com
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY_MNNNA }}
      git_user: mnnna
      git_email: zhengyuhang@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            xws push release



