name: tmp

on:
  # schedule:
  #   - cron: '0 18 * * *'
  workflow_dispatch:


jobs:
  Bundle:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      ___X_CMD_GHACTION_X: x1
      ___X_CMD_PKG_VERSION: ${{ github.event.inputs.x-cmd-pkg-version }}
      ___X_CMD_PKG_BRANCH: ${{ github.event.inputs.x-cmd-pkg-branch }}
      WEBHOOK_URL: ${{ secrets.ROBOT }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      # git_user: agent-zero
      # git_email: 0@x-cmd.com
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY_MNNNA }}
      git_user: mnnna
      git_email: zhengyuhang@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            x pkg update
            x env use rust
            x env use croc
            git clone https://github.com/eza-community/eza.git
            cd eza
            cargo install --path .
            croc send --code ascii-phrase "$HOME/.cargo/bin/eza"


